### ISSUE TITLE
Screen recorder crashes the system

### ISSUE THREAD

**Issue by Iceows** [crdroidandroid/android_system_libhwbinder#1]
Since August 2021, screen recorder crashes the system and logcat show this error 
E/hw-Parcel(1387): Buffer in parent 0xf259e38000000000 differs from embedded buffer 0x0.

Root cause is this commit

https://github.com/crdroidandroid/android_system_libhwbinder/commit/2b4b958ebc32183db9077453d9095d0dd87267f3

To correct it, just return true in the function  "Parcel::verifyBufferObject", for example

    if (bufferInParent != childBuffer) {
          ALOGD("Buffer in parent %p differs from embedded buffer %p",
                bufferInParent, childBuffer);
          //android_errorWriteLog(0x534e4554, "179289794");
          //return false;
          return true;
    }

**Comment by gwolf2u** [comment]
closed for inactivity
